{% set name = "jupyter-server-proxy" %}
{% set pypi_name = name|replace("-", "_") %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 2fc74e099765a7a8a32988610efbf9e4416a366b52215feaa22363ed8ea0fac0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
    - jupyter-packaging
  run:
    - python >=3
    - jupyter_server >=1
    - simpervisor >=0.2
    - aiohttp

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - jupyter_server_proxy

about:
  home: https://github.com/jupyterhub/jupyter-server-proxy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter server extension to supervise and proxy web services
  description: |
    Jupyter Server Proxy lets you run arbitrary external processes (such as
    RStudio, Shiny Server, syncthing, PostgreSQL, etc) alongside your notebook,
    and provide authenticated web access to them.
  doc_url: https://jupyter-server-proxy.readthedocs.io
  dev_url: https://github.com/jupyterhub/jupyter-server-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
    - xhochy
    - consideratio
