{% set name = "jupyter-server-proxy" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyter_server_proxy-{{ version }}.tar.gz
  sha256: e5732eb9c810c0caa997f90a2f15f7d09af638e7eea9c67eb5c43e9c1f0e1157

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .

requirements:
  host:
    - python
    - hatch-jupyter-builder >=0.8.3
    - hatchling >=1.18.0
    - pip
    - jupyterlab >=4.0.6,<5.0.0a0
  run:
    - python
    - aiohttp
    - importlib-metadata >=4.8.3  # [py<310]
    - jupyter_server >=1.24.0
    - simpervisor >=1.0.0
    - tornado >=6.1.0
    - traitlets >=5.1.0
  run_constrained:
    - jupyterlab >=4.0.5,<5.0.0a0
    - notebook >=7
    - robotframework-jupyterlibrary >=0.4.2
    - jupyter-server >=2

test:
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip
    - notebook
  commands:
    - pip check
    # print everything
    - jupyter server extension list  # [not win]
    - jupyter labextension list  # [not win]
    - jupyter notebook extension list  # [not win]
    - jupyter lab extension list  # [not win]
    # validate each  # [not win]
    - jupyter server extension list 1>server_extensions 2>&1  # [not win]
    - cat server_extensions | grep -ie "jupyter_server_proxy.*OK"  # [not win]
    - jupyter labextension list 1>labextensions 2>&1  # [not win]
    - cat labextensions | grep -ie "@jupyterhub/jupyter-server-proxy.*{{ version.replace(".", "\\.") }}.*OK"  # [not win]
    - jupyter notebook extension list 1>notebook_extensions 2>&1  # [not win]
    - cat notebook_extensions | grep -ie "jupyter_server_proxy.*OK"  # [not win]
    - jupyter lab extension list 1>lab_extensions 2>&1  # [not win]
    - cat lab_extensions | grep -ie "jupyter_server_proxy.*OK"  # [not win]
  imports:
    - jupyter_server_proxy

about:
  home: https://github.com/jupyterhub/jupyter-server-proxy
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - labextension/LICENSE
  summary: Jupyter server extension to supervise and proxy web services
  description: |
    Jupyter Server Proxy lets you run arbitrary external processes (such as
    RStudio, Shiny Server, syncthing, PostgreSQL, etc) alongside your notebook,
    and provide authenticated web access to them.
  doc_url: https://jupyter-server-proxy.readthedocs.io
  dev_url: https://github.com/jupyterhub/jupyter-server-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
    - xhochy
    - consideratio
    - bollwyvl
