{% set name = "jupyter-server-proxy" %}
{% set version = "4.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyter_server_proxy-{{ version }}.tar.gz
  sha256: 6fd8ce88a0100e637b48f1d3aa32f09672bcb2813dc057d70567f0a40b1237f5

build:
  number: 0
  # jupyterlab is missing on s390x
  skip: True  # [py<38 or (linux and s390x)]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .

requirements:
  host:
    - python
    - hatch-jupyter-builder >=0.8.3
    - hatchling >=1.18.0
    - pip
  run:
    - python
    - aiohttp
    - importlib-metadata >=4.8.3  # [py<310]
    - jupyter_server >=1.0
    - simpervisor >=1.0
    - tornado >=5.1
    - traitlets >=4.2.1
  run_constrained:
    - jupyterlab >=3,<5
    - notebook >=6,<8

test:
  requires:
    - jupyterlab
    - m2-grep  # [win]
    - pip
  commands:
    - pip check
    # print everything
    - jupyter server extension list
    - jupyter labextension list
    - jupyter notebook extension list
    - jupyter lab extension list
    # validate each
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep -ie "jupyter_server_proxy.*OK"
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep -ie "@jupyterhub/jupyter-server-proxy.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter notebook extension list 1>notebook_extensions 2>&1
    - cat notebook_extensions | grep -ie "jupyter_server_proxy.*OK"
    - jupyter lab extension list 1>lab_extensions 2>&1
    - cat lab_extensions | grep -ie "jupyter_server_proxy.*OK"
  imports:
    - jupyter_server_proxy

about:
  home: https://github.com/jupyterhub/jupyter-server-proxy
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - labextension/LICENSE
  summary: Jupyter server extension to supervise and proxy web services
  description: |
    Jupyter Server Proxy lets you run arbitrary external processes (such as
    RStudio, Shiny Server, syncthing, PostgreSQL, etc) alongside your notebook,
    and provide authenticated web access to them.
  doc_url: https://jupyter-server-proxy.readthedocs.io
  dev_url: https://github.com/jupyterhub/jupyter-server-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
    - xhochy
    - consideratio
    - bollwyvl
