{% set version = "3.2.0" %}

package:
  name: jupyter-server-proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-server-proxy/jupyter-server-proxy-{{ version }}.tar.gz
  sha256: 816262f5711432dd79cbbd81e427cc2b592f522b0fae54368ed6e9d943384327

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps -vv --install-option="--skip-npm" .

requirements:
  host:
    - jupyter-packaging >=0.7,<0.8
    - jupyterlab >=3.0,<4
    - pip
    - python >=3.6
    - setuptools
  run:
    - aiohttp
    - jupyter_server >=1
    - python >=3.6
    - simpervisor >=0.4

test:
  requires:
    - jupyterlab >=3.0,<4
    - m2-grep  # [win]
    - pip
  commands:
    - pip check
    # print everything
    - jupyter labextension list
    - jupyter server extension list
    - jupyter serverextension list
    # validate each
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep -ie "jupyter_server_proxy.*OK"
    - jupyter serverextension list 1>serverextensions 2>&1
    - cat serverextensions | grep -ie "jupyter_server_proxy.*OK"
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep -ie "@jupyterlab/server-proxy.*{{ version.replace(".", "\\.") }}.*OK"
  imports:
    - jupyter_server_proxy

about:
  home: https://github.com/jupyterhub/jupyter-server-proxy
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyter_server_proxy/labextension/static/third-party-licenses.json
  summary: Jupyter server extension to supervise and proxy web services
  description: |
    Jupyter Server Proxy lets you run arbitrary external processes (such as
    RStudio, Shiny Server, syncthing, PostgreSQL, etc) alongside your notebook,
    and provide authenticated web access to them.
  doc_url: https://jupyter-server-proxy.readthedocs.io
  dev_url: https://github.com/jupyterhub/jupyter-server-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
    - xhochy
    - consideratio
    - bollwyvl
