{% set version = "3.2.0" %}

package:
  name: jupyter-server-proxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-server-proxy/jupyter-server-proxy-{{ version }}.tar.gz
  sha256: 30d57976090980f4380cb0a80e8e829dfd74d0a19edb64329239def9feefcde4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
    - jupyter-packaging
    - jupyterlab >=3.0,<4
  run:
    - python >=3
    - jupyter_server >=1
    - simpervisor >=0.4
    - aiohttp

test:
  requires:
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter labextension list
    - jupyter server extension list
    - jupyter serverextension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep -ie "jupyter_server_proxy.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter serverextension list 1>serverextensions 2>&1
    - cat serverextensions | grep -ie "jupyter_server_proxy.*{{ version.replace(".", "\\.") }}.*OK"
    - jupyter labextension list 1>labextensions 2>&1
    - cat serverextensions | grep -ie "@jupyterlab/server-proxy.*{{ version.replace(".", "\\.") }}.*OK"
  imports:
    - jupyter_server_proxy

about:
  home: https://github.com/jupyterhub/jupyter-server-proxy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter server extension to supervise and proxy web services
  description: |
    Jupyter Server Proxy lets you run arbitrary external processes (such as
    RStudio, Shiny Server, syncthing, PostgreSQL, etc) alongside your notebook,
    and provide authenticated web access to them.
  doc_url: https://jupyter-server-proxy.readthedocs.io
  dev_url: https://github.com/jupyterhub/jupyter-server-proxy

extra:
  recipe-maintainers:
    - jakirkham
    - lsetiawan
    - minrk
    - ocefpaf
    - xhochy
    - consideratio
    - bollwyvl
