travis:
  secure:
    BINSTAR_TOKEN: TEH9CxypdtuGPAFPgE9AocaWYa960rc1XhXBY3yakuoN6gRWn4DBQ5zsnHJmkfxSkf8CN3eX86KSZ7FwbdtoU++3Iamki8tZREgnGuLAwhtUpyXVYwTWdMbcNWGG6kcNyxjrUSxm1EXHoOzCi7LigMXz1VDQW3U2pIRbDkHR5My8MiJZaJsMm1f8hCnq2OI6Lvfsp/Nm20VrX3Eh8bcGTIHa1ScfLp771dgHDiZJoXS4KXJCfEzBOeLHSMfjIUtfqnDGCg9n1PXLfUCdlm3v2a/PE8QuAtHe9Dw3ZBbEq7lTQ+nrBv7AZnAffkCJMJ7foIk6hV92knsguIKMsuu/GxlN0PuS0EJ8I5iDI03ODAkehtPDTYyuVc/X4Ez/+2GY+VHj4foqes4+qJLDS55jSpKUyQIo+5Fj0E58mduwdO3ACIeo9WOCTMeWNqHxteq8B5O+8K2/8E4lZjAyfnGK7uvp08AMjuYX7iaA9ElvYowNToPP5WrT9Y5N2ZYiYJ9yAwZvo9WRNdAbiZUK8GG52moB0Q5j/8VJNYEJOB3v/mxb1ltGIgK2eDFJ5pDIjoWKMuCGpdY6huzFLmYROv2SZcpeTcAlVbT7dlXfTnxS8YStldrVRwi1PyUkEhGxrkfuPhYlaOn9BPgGXrTSI0si+fvQjzSEAOHdMxCEpb/OPcs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
